/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        'custom-lavender': '#CDB4DB',
        'custom-pink': '#FFC0CB',
        'custom-lightPink': '#FFAFCC',
        'custom-babyBlue': '#BDE0FE',
        'custom-lightBlue': '#A2D2FF',
        'custom-orange': '#FF9B54',
        'custom-purple': '#9B5DE5',
        'custom-black': '#222222',
        'custom-yellow': '#FEE440',
        'brand-dark': '#333333',
        'brand-accent': '#9B5DE5',
        'brand-bg-light': '#F8F9FA',
      },
      transitionTimingFunction: {
        'cubic-form': 'cubic-bezier(0.645, 0.045, 0.355, 1)',
      },
      boxShadow: {
        'form-soft': '0 10px 25px -5px rgba(0, 0, 0, 0.05), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
        'form-focus': '0 0 0 3px rgba(162, 210, 255, 0.5)',
      },
      borderRadius: {
        'xl': '1rem',
        'lg-form': '0.75rem',
      },
      animation: {
        'float-slow': 'float 6s ease-in-out infinite',
        'float-medium': 'float 5s ease-in-out infinite',
        'float-slow-reverse': 'floatReverse 7s ease-in-out infinite',
        'float-medium-reverse': 'floatReverse 5s ease-in-out infinite',
        'float-random-1': 'floatRandom1 15s ease-in-out infinite alternate',
        'float-random-2': 'floatRandom2 12s ease-in-out infinite alternate',
        'float-random-3': 'floatRandom3 18s ease-in-out infinite alternate',
        'float-random-4': 'floatRandom4 16s ease-in-out infinite alternate',
        'float-random-5': 'floatRandom5 14s ease-in-out infinite alternate',
        'float-random-6': 'floatRandom6 17s ease-in-out infinite alternate',
        'float-random-7': 'floatRandom7 13s ease-in-out infinite alternate',
        'float-random-8': 'floatRandom8 19s ease-in-out infinite alternate',
        'float-moon': 'floatMoon 25s ease-in-out infinite alternate',
        'smoke-1': 'smokeEffect 2s ease-out infinite',
        'smoke-2': 'smokeEffect 2.5s ease-out 0.3s infinite',
        'smoke-3': 'smokeEffect 2.2s ease-out 0.6s infinite',
        'smoke-4': 'smokeEffect 2.4s ease-out 0.9s infinite',
        'smoke-5': 'smokeEffect 2.3s ease-out 1.2s infinite',
        'smoke-pink-1': 'smokeEffect 2.4s ease-out 0.2s infinite',
        'smoke-pink-2': 'smokeEffect 2.6s ease-out 0.5s infinite',
        'smoke-pink-3': 'smokeEffect 2.3s ease-out 0.8s infinite',
        'smoke-pink-4': 'smokeEffect 2.7s ease-out 1.1s infinite',
        'pulse-slow': 'pulseEffect 1.5s ease-in-out infinite',
        'cloud-reveal': 'cloudReveal 2.5s ease-out forwards',
        'fade-in-up': 'fadeInUp 1s ease-out forwards',
        'fade-in-down': 'fadeInDown 1s ease-out forwards',
        'fade-in-left': 'fadeInLeft 1s ease-out forwards',
        'fade-in-right': 'fadeInRight 1s ease-out forwards',
        'scale-in': 'scaleIn 0.7s ease-out forwards',
        'bounce-in': 'bounceIn 1s ease-out forwards',
        'rotate-in': 'rotateIn 1s ease-out forwards',
        'shimmer': 'shimmer 2s linear infinite',
        'float-card': 'floatCard 4s ease-in-out infinite alternate',
        'hover-glow': 'hoverGlow 2s ease-in-out infinite alternate',
        'blob-morph': 'blobMorph 25s ease-in-out infinite alternate',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        floatReverse: {
          '0%, 100%': { transform: 'translateY(-20px)' },
          '50%': { transform: 'translateY(0)' },
        },
        floatRandom1: {
          '0%': { transform: 'translate(0px, 0px) rotate(0deg)' },
          '33%': { transform: 'translate(25px, -15px) rotate(2deg)' },
          '66%': { transform: 'translate(-15px, 10px) rotate(-1deg)' },
          '100%': { transform: 'translate(5px, -25px) rotate(1deg)' },
        },
        floatRandom2: {
          '0%': { transform: 'translate(0px, 0px) rotate(0deg)' },
          '33%': { transform: 'translate(-20px, 10px) rotate(-2deg)' },
          '66%': { transform: 'translate(15px, -5px) rotate(1deg)' },
          '100%': { transform: 'translate(-10px, -15px) rotate(-1deg)' },
        },
        floatRandom3: {
          '0%': { transform: 'translate(0px, 0px) rotate(0deg)' },
          '33%': { transform: 'translate(15px, 10px) rotate(1deg)' },
          '66%': { transform: 'translate(-10px, -20px) rotate(-2deg)' },
          '100%': { transform: 'translate(20px, 5px) rotate(1deg)' },
        },
        floatRandom4: {
          '0%': { transform: 'translate(0px, 0px) rotate(0deg)' },
          '33%': { transform: 'translate(-15px, -10px) rotate(-1deg)' },
          '66%': { transform: 'translate(10px, 15px) rotate(2deg)' },
          '100%': { transform: 'translate(-5px, -5px) rotate(-1deg)' },
        },
        floatRandom5: {
          '0%': { transform: 'translate(0px, 0px) rotate(0deg)' },
          '33%': { transform: 'translate(10px, -20px) rotate(2deg)' },
          '66%': { transform: 'translate(-15px, 5px) rotate(-1deg)' },
          '100%': { transform: 'translate(5px, 15px) rotate(1deg)' },
        },
        floatRandom6: {
          '0%': { transform: 'translate(0px, 0px) rotate(0deg)' },
          '33%': { transform: 'translate(-10px, 15px) rotate(-2deg)' },
          '66%': { transform: 'translate(20px, -10px) rotate(1deg)' },
          '100%': { transform: 'translate(-5px, 5px) rotate(-1deg)' },
        },
        floatRandom7: {
          '0%': { transform: 'translate(0px, 0px) rotate(0deg)' },
          '33%': { transform: 'translate(15px, 5px) rotate(1deg)' },
          '66%': { transform: 'translate(-10px, -15px) rotate(-2deg)' },
          '100%': { transform: 'translate(5px, 10px) rotate(1deg)' },
        },
        floatRandom8: {
          '0%': { transform: 'translate(0px, 0px) rotate(0deg)' },
          '33%': { transform: 'translate(-5px, -10px) rotate(-1deg)' },
          '66%': { transform: 'translate(15px, 5px) rotate(2deg)' },
          '100%': { transform: 'translate(-10px, -5px) rotate(-1deg)' },
        },
        floatMoon: {
          '0%': { transform: 'translate(0, 0) rotate(0deg) scale(1)' },
          '25%': { transform: 'translate(20px, -15px) rotate(4deg) scale(1.03)' },
          '50%': { transform: 'translate(-10px, 15px) rotate(-3deg) scale(1)' },
          '75%': { transform: 'translate(15px, 10px) rotate(2deg) scale(1.02)' },
          '100%': { transform: 'translate(-5px, -20px) rotate(-2deg) scale(1.01)' },
        },
        smokeEffect: {
          '0%': { transform: 'scale(0.8) translate(0, 0)', opacity: 0.8 },
          '100%': { transform: 'scale(3) translate(0, -120px)', opacity: 0 },
        },
        pulseEffect: {
          '0%, 100%': { opacity: 1, transform: 'scale(1)' },
          '50%': { opacity: 0.6, transform: 'scale(1.1)' },
        },
        cloudReveal: {
          '0%': { opacity: 1, transform: 'scale(1.2) translateY(0)' },
          '100%': { opacity: 0, transform: 'scale(0.8) translateY(-100%)' },
        },
        fadeInUp: {
          '0%': { opacity: 0, transform: 'translateY(20px)' },
          '100%': { opacity: 1, transform: 'translateY(0)' },
        },
        fadeInDown: {
          '0%': { opacity: 0, transform: 'translateY(-20px)' },
          '100%': { opacity: 1, transform: 'translateY(0)' },
        },
        fadeInLeft: {
          '0%': { opacity: 0, transform: 'translateX(-20px)' },
          '100%': { opacity: 1, transform: 'translateX(0)' },
        },
        fadeInRight: {
          '0%': { opacity: 0, transform: 'translateX(20px)' },
          '100%': { opacity: 1, transform: 'translateX(0)' },
        },
        scaleIn: {
          '0%': { opacity: 0, transform: 'scale(0.9)' },
          '100%': { opacity: 1, transform: 'scale(1)' },
        },
        bounceIn: {
          '0%': { opacity: 0, transform: 'scale(0.3)' },
          '50%': { opacity: 1, transform: 'scale(1.05)' },
          '70%': { transform: 'scale(0.9)' },
          '100%': { transform: 'scale(1)' },
        },
        rotateIn: {
          '0%': { opacity: 0, transform: 'rotate(-90deg)' },
          '100%': { opacity: 1, transform: 'rotate(0)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        floatCard: {
          '0%': { transform: 'translateY(0)' },
          '100%': { transform: 'translateY(-10px)' },
        },
        hoverGlow: {
          '0%': { boxShadow: '0 0 5px 0 rgba(255, 105, 180, 0.3)' },
          '100%': { boxShadow: '0 0 20px 5px rgba(255, 105, 180, 0.6)' },
        },
        blobMorph: {
          '0%': { borderRadius: '60% 40% 30% 70%/60% 40% 70% 30%' },
          '25%': { borderRadius: '30% 60% 70% 40%/50% 60% 30% 60%' },
          '50%': { borderRadius: '40% 60% 30% 70%/60% 40% 70% 30%' },
          '75%': { borderRadius: '60% 40% 70% 30%/40% 50% 60% 50%' },
          '100%': { borderRadius: '40% 60% 70% 30%/50% 40% 30% 60%' },
        },
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'shimmer-gradient': 'linear-gradient(to right, rgba(255,255,255,0) 0%, rgba(255,255,255,0.5) 50%, rgba(255,255,255,0) 100%)',
      },
    },
  },
  plugins: [],
};